FROM node:20.12.2

WORKDIR /app

# Get the environment variables
# ARG NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN
# ARG NEXT_PUBLIC_CONTENTFUL_SPACE_ID
# ARG NEXT_PUBLIC_CONTENTFUL_PREVIEW
# ARG NEXT_PUBLIC_CONTENTFUL_PREVIEW_TOKEN

# # Set the environment variables
# ENV NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN=$NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN
# ENV NEXT_PUBLIC_CONTENTFUL_SPACE_ID=$NEXT_PUBLIC_CONTENTFUL_SPACE_ID
# ENV NEXT_PUBLIC_CONTENTFUL_PREVIEW=$NEXT_PUBLIC_CONTENTFUL_PREVIEW
# ENV NEXT_PUBLIC_CONTENTFUL_PREVIEW_TOKEN=$NEXT_PUBLIC_CONTENTFUL_PREVIEW_TOKEN

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]