import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Header } from "@/components/Header/Header";
import { ISections } from "@/utils/interfaces";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const headerContent: ISections = {
    "home-section": {
      id: "1",
      name: "Home",
      path: "/",
      appears: true,
    },
    "map-section": {
      id: "2",
      name: "Mapa",
      path: "/mapa",
      appears: true,
    },
    "about-section": {
      id: "3",
      name: "Sobre o SAP",
      path: "/sobre-o-sap",
      appears: true,
    },
    "contact-section": {
      id: "4",
      name: "Contatos",
      path: "/contatos",
      appears: true,
    },
  };
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header content={Object.values(headerContent)}></Header>
        {children}
      </body>
    </html>
  );
}
