import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/NavigationMenu/NavigationMenu";
import { ISection } from "@/utils/interfaces";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navContent: ISection[] = [
  { id: "1", name: "Home", path: "/", appears: true },
  { id: "2", name: "Mapa", path: "/mock", appears: true },
  { id: "3", name: "Sobre o SAP", path: "/mock", appears: true },
  { id: "4", name: "Contatos", path: "/mock", appears: true },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header content={navContent} />
        {children}
      </body>
    </html>
  );
}
