name: CI SAP-Home Frontend

on:
  push:
    branches: ["*"]
    tags: ["*"]

  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Setup npm
        run: npm install -g npm@11.8.0

      - name: Install Dependencies
        run: npm ci

      - name: Run CI verification
        env:
          NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN }}
          NEXT_PUBLIC_CONTENTFUL_PREVIEW: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_PREVIEW }}
          NEXT_PUBLIC_CONTENTFUL_PREVIEW_TOKEN: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_PREVIEW_TOKEN }}
          NEXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_SPACE_ID }}
        run: npm run ci:verify
